[package]
name = "rufi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
license-file = "../LICENSE"

[dependencies]
serde = { version = "1.0.226", default-features = false, features = ["alloc", "derive"] }
